# Generated by Django 6.0.5 on 2026-08-26 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_version',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
