# Generated by Django 6.0.5 on 2026-06-02 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arena_name', models.CharField(max_length=100, unique=True)),
                ('region', models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('eu-central-1', 'EU Central (Frankfurt)'), ('ap-south-1', 'AP South (Mumbai)')], max_length=30)),
                ('max_players', models.PositiveIntegerField(default=1000)),
                ('risk_profile', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('liquidity_seed', models.DecimalField(decimal_places=2, default=50000, max_digits=12)),
                ('instance_id', models.CharField(blank=True, max_length=30, null=True)),
                ('instance_type', models.CharField(blank=True, max_length=20)),
                ('public_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('private_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('launching', 'Launching'), ('warming', 'Warming'), ('healthy', 'Healthy'), ('degraded', 'Degraded'), ('stopping', 'Stopping'), ('stopped', 'Stopped'), ('terminated', 'Terminated'), ('failed', 'Failed')], default='launching', max_length=20)),
                ('latency_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Game Server',
                'verbose_name_plural': 'Game Servers',
                'ordering': ['-created_at'],
            },
        ),
    ]
