# Generated by Django 6.0.5 on 2026-08-25 14:56

import django.db.models.deletion
import django_mongodb_backend.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('bet_debit', 'Bet Placed'), ('win_credit', 'Win Credited'), ('refund', 'Refund')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('provider', models.CharField(choices=[('razorpay', 'razorpay'), ('cashfree', 'cashfree')], default='razorpay', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cashfree_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cashfree_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cashfree_payment_session_id', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('bank_account', 'Bank Account')], default='upi', max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_response', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='wallet.wallet')),
            ],
        ),
    ]
