# Generated by Django 6.0.5 on 2026-05-19 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('mode', models.CharField(choices=[('upi', 'UPI'), ('bank_account', 'Bank Account')], default='upi', max_length=15)),
                ('upi_id', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=15, null=True)),
                ('account_holder', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payout_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payout_response', models.JSONField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_requests', to='wallet.wallet')),
            ],
        ),
    ]
