# Generated by Django 6.0.5 on 2026-08-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_transaction_balance_after_transaction_balance_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='cashfree_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cashfree_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cashfree_payment_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='provider',
            field=models.CharField(choices=[('razorpay', 'razorpay'), ('cashfree', 'cashfree')], default='razorpay', max_length=20),
        ),
    ]
