# Generated by Django 6.0.5 on 2026-05-20 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variation', models.CharField(choices=[('V1', 'Single'), ('V2', 'Pair'), ('V3', 'Trio'), ('V4', 'Sum Matka'), ('V5', 'Jackpot')], max_length=2)),
                ('status', models.CharField(choices=[('betting_open', 'Betting Open'), ('drawing', 'Drawing'), ('completed', 'Completed')], default='betting_open', max_length=20)),
                ('server_seed', models.CharField(max_length=64)),
                ('seed_hash', models.CharField(max_length=64)),
                ('drawn_numbers', models.JSONField(blank=True, null=True)),
                ('winners_data', models.JSONField(blank=True, null=True)),
                ('draw_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_numbers', models.JSONField()),
                ('entry_fee', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10)),
                ('reward_amount', models.PositiveIntegerField(default=0)),
                ('win_type', models.CharField(blank=True, max_length=30)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='game.round')),
            ],
            options={
                'ordering': ['placed_at'],
            },
        ),
    ]
