# Generated by Django 6.0.5 on 2026-08-25 14:56

import django.db.models.deletion
import django_mongodb_backend.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variation', models.CharField(choices=[('V1', 'Single'), ('V2', 'Pair'), ('V3', 'Trio'), ('V4', 'Sum Matka'), ('V5', 'Jackpot')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_fee', models.PositiveIntegerField(default=10)),
                ('max_players', models.PositiveIntegerField(default=100)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('rounds_count', models.PositiveIntegerField(default=10)),
                ('round_duration_seconds', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='game.game')),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variation', models.CharField(choices=[('V1', 'Single'), ('V2', 'Pair'), ('V3', 'Trio'), ('V4', 'Sum Matka'), ('V5', 'Jackpot')], max_length=2)),
                ('status', models.CharField(choices=[('betting_open', 'Betting Open'), ('drawing', 'Drawing'), ('completed', 'Completed')], default='betting_open', max_length=20)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('server_seed', models.CharField(max_length=64)),
                ('seed_hash', models.CharField(max_length=64)),
                ('drawn_numbers', models.JSONField(blank=True, null=True)),
                ('winners_data', models.JSONField(blank=True, null=True)),
                ('draw_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.pool')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_numbers', models.JSONField()),
                ('entry_fee', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('won', 'Won'), ('lost', 'Lost')], default='pending', max_length=10)),
                ('reward_amount', models.PositiveIntegerField(default=0)),
                ('win_type', models.CharField(blank=True, max_length=30)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('points_earned', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to=settings.AUTH_USER_MODEL)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.pool')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bets', to='game.round')),
            ],
            options={
                'ordering': ['placed_at'],
            },
        ),
        migrations.CreateModel(
            name='PoolParticipant',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('reward_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='game.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'joined_at'],
                'unique_together': {('pool', 'user')},
            },
        ),
    ]
