# Generated by Django 6.0.5 on 2026-07-10 11:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('variation', models.CharField(choices=[('V1', 'Single'), ('V2', 'Pair'), ('V3', 'Trio'), ('V4', 'Sum Matka'), ('V5', 'Jackpot')], max_length=2)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='round_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entry_fee', models.PositiveIntegerField(default=10)),
                ('max_players', models.PositiveIntegerField(default=100)),
                ('duration_minutes', models.PositiveIntegerField(default=5)),
                ('rounds_count', models.PositiveIntegerField(default=10)),
                ('round_duration_seconds', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed')], default='upcoming', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='game.game')),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bets', to='game.pool'),
        ),
        migrations.AddField(
            model_name='round',
            name='pool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.pool'),
        ),
        migrations.CreateModel(
            name='PoolParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('total_points', models.IntegerField(default=0)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('reward_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='game.pool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pool_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-total_points', 'joined_at'],
                'unique_together': {('pool', 'user')},
            },
        ),
    ]
