# Generated by Django 6.0.5 on 2026-09-09 10:51

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bet',
            options={'ordering': ['-placed_at']},
        ),
        migrations.RemoveField(
            model_name='bet',
            name='pool',
        ),
        migrations.AddField(
            model_name='game',
            name='bg_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='game',
            name='pool_value',
            field=models.CharField(blank=True, default='🪙2,109', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='reward_label',
            field=models.CharField(blank=True, default='10x', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='rewards',
            field=models.CharField(blank=True, default='30x', max_length=50),
        ),
        migrations.AddField(
            model_name='game',
            name='sphere_colors',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='game',
            name='sub_title',
            field=models.CharField(blank=True, default='ENTRY FEES.🪙100', max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='is_recurring',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='slot_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pool',
            name='win_prize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bet',
            name='reward_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='bet',
            name='win_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pool',
            name='rounds_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
