# Generated by Django 6.0.5 on 2026-09-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_bet_options_remove_bet_pool_game_bg_colors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='country',
            field=models.CharField(blank=True, default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='daily_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='is_daily_mega',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='once_per_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pool',
            name='pool_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('mega_daily', 'Daily Mega Pool')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='pool',
            name='prize_distribution',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
