# Generated by Django 6.0.5 on 2026-09-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_pool_country_pool_daily_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='pool',
            name='max_players',
            field=models.PositiveIntegerField(default=150),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('mega_daily', 'Daily Mega Pool'), ('hourly', 'Hourly Pool'), ('2_hourly', '2-Hourly Pool'), ('5_hourly', '5-Hourly Pool'), ('10_hourly', '10-Hourly Pool'), ('regular_5min', 'Regular Pool')], default='standard', max_length=30),
        ),
        migrations.AlterField(
            model_name='pool',
            name='rounds_count',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
