# Generated by Django 6.0.5 on 2026-09-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_alter_pool_duration_minutes_alter_pool_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='rounds_count',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
