# Generated by Django 6.0.5 on 2026-09-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_alter_pool_rounds_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pool',
            name='max_players',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('mega_daily', 'Daily Mega Pool'), ('regular_pool', 'Regular Pool')], default='standard', max_length=30),
        ),
    ]
