# Generated by Django 6.0.5 on 2026-09-21 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_pool_duration_minutes_alter_pool_max_players_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
