# Generated by Django 6.0.5 on 2026-09-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_pool_duration_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='interval_minutes',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='pool',
            name='is_entry_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pool',
            name='scheduled_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pool',
            name='pool_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('mega_daily', 'Daily Mega Pool'), ('regular_pool', 'Regular Pool'), ('hourly_pool', 'Hourly Pool')], default='standard', max_length=30),
        ),
        migrations.AlterField(
            model_name='pool',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('active', 'Active'), ('completed', 'Completed'), ('disabled', 'Disabled')], default='upcoming', max_length=20),
        ),
    ]
