"""
Django settings for matka_the_game_of_cards project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
import dj_database_url
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-wgtb+t&m5@w%!xs$6ppo+lu9uu+rj5v&!-$dzy)yiv5vmc^y&6'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

AUTH_USER_MODEL = 'auths.User'

# Application definition

INSTALLED_APPS = [
    'matka_the_game_of_cards.apps.MongoAdminConfig',
    'matka_the_game_of_cards.apps.MongoAuthConfig',
    'matka_the_game_of_cards.apps.MongoContentTypesConfig',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_celery_beat',
    'channels',
    
    'auths',
    'game',

    'wallet',
    'servers',
    'policies',


]



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True   # change to CORS_ALLOWED_ORIGINS = [...] in production

CORS_ALLOWED_METHODS = ['DELETE', 'GET', 'OPTIONS', 'PATCH', 'POST', 'PUT']

CORS_ALLOWED_HEADERS = [
    'authorization',
    'content-type',   # fixed: was missing — causes 400 on JSON POST
    'x-requested-with',
    'accept',
]


ROOT_URLCONF = 'matka_the_game_of_cards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'matka_the_game_of_cards.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('NAME'),
#         'USER': os.getenv('USER'),
#         'PASSWORD': os.getenv('PASSWORD'),
#         'HOST': os.getenv('HOST'),
#         'PORT': os.getenv('PORT'),
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django_mongodb_backend',
        'HOST': os.getenv('MONGODB_URI', 'mongodb://localhost:27017/'),
        'NAME': os.getenv('MONGODB_NAME', 'matka_db'),
    },
    'sqlite': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_ROUTERS = ['matka_the_game_of_cards.routers.DatabaseRouter']

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# JWT token lifetimes
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,       # issue new refresh on every refresh call
    'BLACKLIST_AFTER_ROTATION': True,    # blacklist old refresh tokens
    'AUTH_HEADER_TYPES': ('Bearer',),
}


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

FRONTEND_URL = os.getenv('FRONTEND_URL')

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'undaviyaraj2000@gmail.com'      # ← apni Gmail yahan dalo
EMAIL_HOST_PASSWORD = 'iryccrgewlumzzch'       # ← 16-digit Gmail App Password
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


PHONEPE_MERCHANT_ID = os.getenv('PHONEPE_MERCHANT_ID', 'MERCANT_ID')
PHONEPE_SALT_KEY = os.getenv('PHONEPE_SALT_KEY', 'test-salt')
PHONEPE_API_URL = os.getenv('PHONEPE_API_URL', 'https://api-preprod.phonepe.com/apis/pg-sandbox')
PHONEPE_PAYOUT_ENABLED = os.getenv('PHONEPE_PAYOUT_ENABLED', 'False').lower() in ('true', '1', 't')

CASHFREE_APP_ID = os.getenv('CASHFREE_APP_ID')
CASHFREE_SECRET_KEY = os.getenv('CASHFREE_SECRET_KEY')
CASHFREE_PAYOUT_CLIENT_ID = os.getenv('CASHFREE_PAYOUT_CLIENT_ID')
CASHFREE_PAYOUT_CLIENT_SECRET_KEY = os.getenv('CASHFREE_PAYOUT_CLIENT_SECRET_KEY')
CASHFREE_MODE = os.getenv('CASHFREE_MODE', 'sandbox')
CASHFREE_API_VERSION = os.getenv('CASHFREE_API_VERSION', '2022-01-01')

# settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# ── Django Channels ──────────────────────────────────────────────────
# HTTP + WebSocket dono handle karne ke liye ASGI use karo
ASGI_APPLICATION = 'matka_the_game_of_cards.asgi.application'

# Redis Channel Layer — WebSocket broadcast ke liye
# Redis broker wahi use kar rahe hain jo Celery ke liye hai (db 0)
# Channel Layer alag db (db 1) use karta hai — conflict avoid karne ke liye
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
            "capacity": 1500,       # max messages per channel
            "expiry": 10,           # seconds before unread message expires
        },
    }
}

import environ
env = environ.Env()
environ.Env.read_env()  # .env file read karega
 
# AWS Credentials — KABHI hardcode mat karo
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_ACCESS_KEY_ID     = os.getenv("AWS_ACCESS_KEY_ID")
 
# Tumhare game servers ki default config
AWS_DEFAULT_REGION    = os.getenv("AWS_DEFAULT_REGION", default="us-east-1")
AWS_AMI_ID            = os.getenv("AWS_AMI_ID")           # ami-0xxxxxxxx
AWS_KEY_PAIR          = os.getenv("AWS_KEY_PAIR")          # "matka-game-key"
AWS_SECURITY_GROUP_ID = os.getenv("AWS_SECURITY_GROUP_ID") # "sg-xxxxxxxx"
AWS_SUBNET_ID         = os.getenv("AWS_SUBNET_ID")         # "subnet-xxxxxxxx"

# ── MongoDB Migrations for Contrib Apps ──
MIGRATION_MODULES = {
    'admin': 'mongo_migrations.admin',
    'auth': 'mongo_migrations.auth',
    'contenttypes': 'mongo_migrations.contenttypes',
}